//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loogan.Web.UI.Resources.Pages.LeftSideBar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LeftSideBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeftSideBar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loogan.Web.UI.Resources.Pages.LeftSideBar.LeftSideBar", typeof(LeftSideBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Stream.
        /// </summary>
        public static string ActivityStreamKey {
            get {
                return ResourceManager.GetString("ActivityStreamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string CalendarKey {
            get {
                return ResourceManager.GetString("CalendarKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursesKey {
            get {
                return ResourceManager.GetString("CoursesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string GradesKey {
            get {
                return ResourceManager.GetString("GradesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Page.
        /// </summary>
        public static string InstitutionPageKey {
            get {
                return ResourceManager.GetString("InstitutionPageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesKey {
            get {
                return ResourceManager.GetString("MessagesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgnizations.
        /// </summary>
        public static string OrgnizationsKey {
            get {
                return ResourceManager.GetString("OrgnizationsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutKey {
            get {
                return ResourceManager.GetString("SignOutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsKey {
            get {
                return ResourceManager.GetString("ToolsKey", resourceCulture);
            }
        }
    }
}
